[book]
title = "RuxOS Book"
authors = ["yanjuguang"]
language = "en"
description = "RuxOS guide book"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/syswonder/ruxos"
git-repository-icon = "fa-github"
